import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {replay} from '../scripts/accountability.mjs';
const read=name=>JSON.parse(readFileSync(new URL(`../src/data/${name}.json`,import.meta.url),'utf8'));
const baseline=read('intelligence'), links=read('thread-links');
const journal=read('history');journal.events=journal.events.slice(0,83);
const run=events=>replay(baseline,{...journal,events},links);
const hash=value=>createHash('sha256').update(JSON.stringify(value)).digest('hex');

test('all 83 accepted events, current records and historical snapshots retain pre-fix projection',()=>{
  assert.equal(journal.events.length,83);
  // Captured from the unchanged reducer at public7b688e3, not regenerated by tests.
  assert.equal(hash(run(journal.events)),'c2a5b9f94b40297d581b95ef5d99158c3db6286638a984ec24b4b9d66915b302');
});
test('every historical prefix produces the identical immutable record version',()=>{
  const full=run(journal.events);
  for(let count=1;count<=83;count++) {
    const last=journal.events[count-1], key={signal:'signals',thread:'threads',prediction:'predictions'}[last.record_type];
    const prefix=run(journal.events.slice(0,count));
    const version=last.expected_version+1;
    assert.deepEqual(prefix.versions[key][last.record_id][version],full.versions[key][last.record_id][version]);
  }
});
test('modified historic payload or copied ID cannot gain legacy clearance',()=>{
  const index=journal.events.findIndex(e=>e.kind==='revise'&&e.record_type==='thread');
  const prefix=journal.events.slice(0,index), original=journal.events[index];
  const before=run(prefix).data.threads.find(t=>t.id===original.record_id);
  for (const mutate of [e=>e.note+=' Modified.',e=>e.id='evt-copied-legacy-shape',e=>e.payload.summary='Changed payload',e=>e.recorded_at=new Date(Date.parse(e.recorded_at)+1).toISOString()]) {
    const changed=structuredClone(original);mutate(changed);
    const after=run([...prefix,changed]).data.threads.find(t=>t.id===original.record_id);
    for (const field of ['last_reviewed_at','last_review_outcome','review_required','next_review_at','review_due_since'])
      assert.deepEqual(after[field],before[field]);
  }
});
test('new same-time revision after the accepted boundary preserves unresolved Beam obligation',()=>{
  const before=run(journal.events), beam=before.data.threads.find(t=>t.id==='thread-open-weight-capability-cost-frontier');
  assert.ok(beam?.review_required,'fixture needs the real unresolved Beam Thread');
  const e={...structuredClone(journal.events.find(e=>e.kind==='revise'&&e.record_type==='thread')),
    id:'evt-synthetic-boundary-attempt',record_id:beam.id,expected_version:beam.version,
    recorded_at:journal.events.at(-1).recorded_at,payload:{effect_on_thesis:'unchanged'}};
  const after=run([...journal.events,e]);const current=after.data.threads.find(t=>t.id===beam.id);
  for (const field of ['last_reviewed_at','last_review_outcome','review_required','next_review_at','review_due_since'])
    assert.deepEqual(current[field],beam[field]);
  assert.deepEqual(after.data.predictions.map(p=>[p.id,p.initial_probability,p.deadline,p.success_criterion,p.failure_criterion,p.resolution_sources]),
    before.data.predictions.map(p=>[p.id,p.initial_probability,p.deadline,p.success_criterion,p.failure_criterion,p.resolution_sources]));
  const backdated=structuredClone(e);backdated.recorded_at='2026-10-07T00:00:00Z';
  assert.throws(()=>run([...journal.events,backdated]),/time reversal/);
});

const thread=(result,id)=>result.data.threads.find(r=>r.id===id);
const sameClocks=(a,b)=>{for(const key of ['last_reviewed_at','last_review_outcome','review_required','next_review_at','review_due_since']) assert.deepEqual(a[key],b[key]);};
test('inserted same-time dependency warning is not cleared by unchanged legacy ID and payload',()=>{
  const original=journal.events[1],prefix=journal.events.slice(0,1);
  const sigId=links[original.record_id].supporting[0];assert.ok(sigId);
  const signal=run(prefix).data.signals.find(r=>r.id===sigId);
  const inserted={...structuredClone(original),id:'evt-independent-inserted-warning',record_type:'signal',record_id:sigId,
    expected_version:signal.version,payload:{summary:`${signal.summary} Synthetic bounded change.`}};
  const before=thread(run([...prefix,inserted]),original.record_id);assert.equal(before.review_required,true);
  const after=thread(run([...prefix,inserted,original]),original.record_id);
  sameClocks(after,before);assert.equal(after.review_required,true);
});

test('reordered same-time distinct-record prefix defeats unchanged later compatibility',()=>{
  const es=structuredClone(journal.events.slice(0,59));
  assert.equal(es[56].recorded_at,es[57].recorded_at);
  assert.notEqual(es[56].record_id,es[57].record_id);
  [es[56],es[57]]=[es[57],es[56]];
  for(let i=56;i<59;i++) sameClocks(thread(run(es.slice(0,i+1)),es[i].record_id),thread(run(es.slice(0,i)),es[i].record_id));
});
